import { 
  Ionicons, FontAwesome, MaterialIcons, MaterialCommunityIcons, 
  Entypo, AntDesign, FontAwesome5, SimpleLineIcons, Octicons 
} from "@expo/vector-icons";
// Nota: Importa tu logo desde la ruta correcta
import logo from "../assets/images/ciudad-verde.png"; 

export const v = {
  // Iconos: Estructura { name: string, pack: Component }
  iconoBuscar: { name: "search", pack: FontAwesome },
  iconoagregar: { name: "plus", pack: AntDesign },
  iconoimagenvacia: { name: "image", pack: MaterialCommunityIcons },
  iconoemijivacio: { name: "emoji-emotions", pack: MaterialIcons },
  iconoreportes: { name: "analytics", pack: Ionicons },
  iconoempresa: { name: "building", pack: FontAwesome5 },
  iconocategorias: { name: "category", pack: MaterialIcons },
  iconomarca: { name: "brand-bitbucket", pack: FontAwesome5 },
  iconoprecioventa: { name: "money-bill-alt", pack: FontAwesome5 },
  iconopreciocompra: { name: "money-bill", pack: FontAwesome5 },
  iconocodigointerno: { name: "codepen", pack: FontAwesome5 },
  iconocodigobarras: { name: "barcode", pack: AntDesign },
  iconostockminimo: { name: "bell-minus", pack: MaterialCommunityIcons },
  iconostock: { name: "reorder-horizontal", pack: MaterialCommunityIcons },
  icononombre: { name: "drive-file-rename-outline", pack: MaterialIcons },
  iconoemail: { name: "alternate-email", pack: MaterialIcons },
  iconopass: { name: "lock-outline", pack: MaterialIcons },
  iconoFlechabajo: { name: "arrow-drop-down", pack: MaterialIcons },
  iconocorona: { name: "crown", pack: FontAwesome5 },
  iconoUser: { name: "user-circle", pack: FontAwesome5 },
  iconoSettings: { name: "settings", pack: Ionicons },
  iconoCerrarSesion: { name: "exit-to-app", pack: MaterialIcons },
  iconofotovacia: { name: "image", pack: MaterialIcons },
  agregar: { name: "plus", pack: AntDesign },
  iconosupabase: { name: "database", pack: FontAwesome5 },
  iconoreact: { name: "react", pack: FontAwesome5 },
  flechaabajolarga: { name: "arrow-down", pack: FontAwesome },
  flechaarribalarga: { name: "arrow-up", pack: FontAwesome },
  balance: { name: "balance-scale", pack: FontAwesome5 },
  iconogoogle: { name: "google", pack: FontAwesome },
  iconocerrar: { name: "close", pack: Ionicons },
  iconoguardar: { name: "save", pack: MaterialIcons },
  iconoayuda: { name: "question-circle", pack: FontAwesome },
  iconopie: { name: "pie-chart", pack: Ionicons },
  iconolineal: { name: "graph", pack: SimpleLineIcons },
  iconobars: { name: "bar-chart", pack: Ionicons },
  iconocalculadora: { name: "calculator", pack: AntDesign },
  iconocheck: { name: "calendar-check", pack: FontAwesome5 },
  iconoflechaderecha: { name: "arrow-forward", pack: Ionicons },
  iconoflechaizquierda: { name: "arrow-back", pack: Ionicons },
  iconoprev: { name: "navigate-before", pack: MaterialIcons },
  icononext: { name: "navigate-next", pack: MaterialIcons },
  iconotodos: { name: "border-all", pack: MaterialIcons },

  // Colores y valores numéricos
  colorSecundario: `#DAC1FF`,
  colorPrincipal: `#027ADE`,
  sidebarWidth: 300,
  smSpacing: 8,
  mdSpacing: 16,
  lgSpacing: 24,
  xlSpacing: 32,
  xxlSpacing: 48,
  borderRadius: 6,
  colorIngresos: `#53B257`,
  colorbgingresos: `#e6ffe7`,
  colorGastos: `#fe6156`,
  colorbgGastos: `#fbcbc9`,
  colorError: `#F54E41`,
  colorExito: `#9046FF`,
  
  // Breakpoints (usar números simples)
  bpmaggie: 240,
  bplisa: 480,
  bpbart: 768,
  bpmarge: 992,
  bphomer: 1200,

  // Estilos visuales
  logo: logo,
  colorselector: "#BF94FF",
  rgbafondos: "rgba(210, 110, 249, 0.1)",
  verde: `#53B257`,
  rojo: `#F54E41`,
};